name: CompileOnRelease
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  buildWindows:
    name: Windows Release
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run release:win
  buildLinux:
    name: Linux Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run release:linux
  buildMacOS:
    name: MacOS Release
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run release:mac
